### ISSUE TITLE
This sentence will likely fail to render...

### ISSUE THREAD

**Issue by nic-hartley** [adobe-fonts/source-code-pro#271] opened 2021-04-06 17:02 UTC
...if written in Source Code Pro, at least.

Here's how it looks in Source Code Pro:

![image](https://user-images.githubusercontent.com/4331760/113748864-fc00a300-96d6-11eb-856e-f9b3cd6609cc.png)

And here's how it looks in a normal font:

![image](https://user-images.githubusercontent.com/4331760/113749058-310cf580-96d7-11eb-874b-0b8c8fc14def.png)

This has something to do with my editor rendering whitespace -- without the dot representing a space character, it renders fine:

![image](https://user-images.githubusercontent.com/4331760/113749839-19823c80-96d8-11eb-9317-c5a548c88908.png)

Unfortunately I have no idea what character that is or how to reproduce it except with the "render whitespace" option. 

In any case, turning the three characters `l[dot]l` into an unreadable _one character wide_ script "H"-looking ligature seems like a bug. It doesn't occur with any other font I've tried. It still selects as three characters, takes three keypresses to go past, etc. In a monospace font this is especially weird; why are there _any_ three-letter ligatures which are one letter wide? And more importantly, is there a way to disable this behavior somehow? Or a variant of Source Code Pro without this ligature?

**Comment by frankrolf** [comment] 2021-04-06 18:14
Duplicate of #260

**Comment by pauldhunt** [comment] 2021-04-07 02:09
Closing because this is a duplicate issue, please see issue #260 for response.

**Closed** 2021-04-07 02:09 UTC
Labels: duplicate
