### ISSUE TITLE
macOS Font Validation fails, "3 serious errors...Do not use these fonts"?

### ISSUE THREAD

**Issue by davidvasquez-epitomyze** [adobe-fonts/source-code-pro#178] opened 2017-10-23 02:36 UTC
"SourceCodeVariable-Roman.otf" fails Font Validation, with three reported problems:

1. 'sfint' required tables
2. 'maxp' table structure
3. System Validation

Font Book warns, "3 serious errors were found. Do not use these fonts."

macOS High Sierra, Version 10.13

Downloaded and attempted to install fresh copy of "SourceCodeVariable-Roman.otf" today (Oct-22-2017).

**Comment by davidvasquez-epitomyze** [comment] 2017-10-23 02:58
Follow-up:

The previous release "2.030R-ro/1.050R-it" found on the "All Releases" page, installs on macOS High Sierra 10.13 without errors:

https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip

Perhaps the Latest Release page should list the previous release for macOS, until the variable version is fixed?

**Comment by miguelsousa** [comment] 2017-10-23 03:44
The variable fonts are not broken. It's macOS that does not support the OpenType-CFF2 format yet.

Duplicate of #167 and #177.

**Closed by miguelsousa** 2017-10-23 03:44 UTC

**Comment by davidvasquez-epitomyze** [comment] 2017-10-23 03:55
That's wonderful that you understand the issue - and certainly your prerogative to close this issue without any further action.

Nevertheless, the "Latest Release" does not work on macOS (nor on Windows 10) - and visitors to your site are still being directed to download a font that doesn't install.

It's safe to say that you'll see this issue reported a number of times, so why not be proactive about it?

Instead of closing duplicates of this issue as they keep coming in, wouldn't it be easier to simply update the "Latest Release" link to point at the most recent version that actually works on macOS and Windows 10?

**Comment by miguelsousa** [comment] 2017-10-23 06:36
> wouldn't it be easier to simply update the "Latest Release" link to point at the most recent version that actually works on macOS and Windows 10?

No, because then there would be people opening issues about not finding the variable font release. It also wouldn't solve the fact that https://github.com/adobe-fonts/source-code-pro/releases/latest points to that release because, well, it's the latest.

Anyway, I took your suggestion about being proactive and added a new paragraph to the latest release's release notes.
