### ISSUE TITLE
Symbols as █▓▒░ don't join vertically

### ISSUE THREAD

**Issue by h-h-h-h** [adobe-fonts/source-code-pro#103] opened 2015-08-15 13:11 UTC
Hello,

the symbols listed in the title and similar ones don't join vertically while box drawing symbols like │║ do.

These fonts do join them in both directions:
- Consolas
- Lucida Console
- Courier New

Test text:
```
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
│██▓▓▒▒░░║
```

Having these symbols joined vertically would be useful, e.g., for seamless bar graphs. If you want seamed bar graphs, there are symbols with a shorter height useful for that purpose.

**Comment by frankrolf** [comment] 2015-08-15 15:54
This issue has been mentioned a couple times before, it really depends on the environment if those characters overlap or not. 

Nevertheless, I think I finally have an idea how to fix this. The challenge is aligning the diagonal, cross-hatched pattern in a way that it is seamless. 

Right now, they will align when you set your line distance to the point size (compressed setting, e.g. 10 on 10pt).

I will modify the pattern in a way that it will match for even values, e.g. 10 on 12 pt, 10 on 14pt and so forth.

**Comment by h-h-h-h** [comment] 2015-08-15 16:45
Here on GitHub I see line spacing, but *in Windows' Notepad there's no line spacing* so the box drawing symbols build a solid line. The other symbols, however, build gaps on the y-axis in Notepad. Isn't this an issue of the character shape (the black rectangle height)?

If you are speaking of some font design internals, however, it would be great to just hear that this will solve the issue.

**Comment by frankrolf** [comment] 2015-12-18 09:56
Duplicate of issue #57.
Tracking the progress in original issue and closing this one.

**Closed by frankrolf** 2015-12-18 09:56 UTC
